version: '3.7'

services:
  blog-backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.test
    container_name: blog-backend
    image: blog-backend:latest
    networks:
      - blog-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/health" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
    ports:
      - "8081:8081"
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: blog-db
    networks:
      - blog-net
    env_file: .env.test
    ports:
      - "5433:5432"
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - /var/lib/data/docker/volumes/blog/postgres:/var/lib/postgresql/data

networks:
  blog-net:
    driver: bridge